const fs = require('fs');
const path = require('path');

function pathValidate(filepath) {
    return filepath && fs.existsSync(filepath)
}

function generateBootstrapIndex() {
    const dstPath = path.resolve(process.env.BOOTSTRAP_IMPORT_THEMES_STYLES);
    const dstFilePath = path.join(dstPath, '_index.scss');
    const srcPath = path.resolve(process.env.BOOTSTRAP4_IMPORT);
    const relativePath = path.relative(dstPath, srcPath);

    [dstPath, dstFilePath, srcPath].forEach(p => {
        if (!pathValidate(p)) {
            throw new Error(`❌ Path tidak tersedia : ${p}`)
        }
    });

    const imports = ['mixins', 'functions', 'variables']
        .map(file => `@import "${relativePath}/${file}";`)
        .join('\n');

    const content = [
        '// index.scss',
        '',
        '// Generated by Command',
        `// Timestamp: ${new Date().toISOString()}`,
        '',
        imports
    ].join('\n');

    try {
        fs.writeFileSync(dstFilePath, content, 'utf8');
        console.log(`✅ File berhasil disimpan: ${dstFilePath}`);
        return true;
    } catch (error) {
        console.error(`❌ Gagal menyimpan file: ${error.message}`);
        return false;
    }
}

module.exports.ThemeImport = {
    build: function () {
        generateBootstrapIndex();
    }
}